from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from typing import List, Dict

class SlideGenerator:
    """
    構造化データからPowerPointスライドを生成するクラス
    """
    def __init__(self):
        self.prs = Presentation()

    def create_slides(self, title: str, slides_data: List[Dict]):
        """
        スライドを作成する
        :param title: プレゼンテーション全体のタイトル
        :param slides_data: スライドのリスト。各スライドは {"title": str, "content": str (箇条書き), "caption": str} の形式
        :return: 保存されたPPTXファイルのパス
        """
        # タイトルスライド
        title_slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by AI Summarizer"

        # コンテンツスライド
        bullet_slide_layout = self.prs.slide_layouts[1]

        for slide_info in slides_data:
            slide = self.prs.slides.add_slide(bullet_slide_layout)
            
            # タイトル
            slide.shapes.title.text = slide_info.get("title", "No Title")
            
            # 本文（箇条書き）
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.text = slide_info.get("content", "")
            
            # ノート（キャプション/概要）を追加
            if "caption" in slide_info:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = slide_info["caption"]
                
            # 図解指示もノートに追加
            if "visual_logic" in slide_info:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                current_note = text_frame.text
                text_frame.text = f"{current_note}\n\n[図解指示]\n{slide_info['visual_logic']}"

        output_path = "generated_presentation.pptx"
        self.prs.save(output_path)
        return output_path

if __name__ == "__main__":
    # Test
    gen = SlideGenerator()
    data = [
        {
            "title": "スライド1のタイトル", 
            "content": "・ポイント1\n・ポイント2", 
            "caption": "これはスライド1の概要です。",
            "visual_logic": "diagram: 対比図\nillustration: 笑顔の高齢者"
        },
        {
            "title": "スライド2のタイトル", 
            "content": "・ポイントA\n・ポイントB", 
            "caption": "これはスライド2の概要です。"
        }
    ]
    gen.create_slides("テストプレゼン", data)
    print("Test PPTX generated.")
