from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from typing import List, Dict

class SlideGenerator:
    """
    構造化データからPowerPointスライドを生成するクラス
    """
    def __init__(self):
        self.prs = Presentation()

    def create_slides(self, title: str, slides_data: List[Dict]):
        """
        スライドを作成する
        :param title: プレゼンテーション全体のタイトル
        :param slides_data: スライドのリスト。各スライドは {"title": str, "content": str (箇条書き), "caption": str} の形式
        :return: 保存されたPPTXファイルのパス
        """
        # メイリオなどの日本語フォントを指定
        FONT_NAME = "Meiryo"

        # --- タイトルスライド ---
        title_slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(title_slide_layout)
        
        # タイトル設定
        title_shape = slide.shapes.title
        title_shape.text = title
        # フォーマット適用
        for paragraph in title_shape.text_frame.paragraphs:
            paragraph.font.name = FONT_NAME
            paragraph.font.size = Pt(44)
            paragraph.font.bold = True

        # サブタイトル設定
        subtitle = slide.placeholders[1]
        subtitle.text = "Generated by AI Summarizer"
        for paragraph in subtitle.text_frame.paragraphs:
            paragraph.font.name = FONT_NAME
            paragraph.font.size = Pt(20)

        # --- コンテンツスライド ---
        bullet_slide_layout = self.prs.slide_layouts[1]

        for slide_info in slides_data:
            slide = self.prs.slides.add_slide(bullet_slide_layout)
            
            # --- スライドタイトル ---
            title_shape = slide.shapes.title
            title_text = slide_info.get("title", "No Title")
            title_shape.text = title_text
            
            # タイトルの位置やサイズを微調整（オプション）
            # title_shape.top = Inches(0.5) 
            
            # タイトルフォント設定
            title_tf = title_shape.text_frame
            title_tf.word_wrap = True # 折り返し有効化
            for paragraph in title_tf.paragraphs:
                paragraph.font.name = FONT_NAME
                paragraph.font.size = Pt(36)
                paragraph.font.bold = True
            
            # --- 本文（箇条書き） ---
            body_shape = slide.placeholders[1]
            # 本文エリアの位置調整（少し下げる・広げるなど）
            body_shape.top = Inches(1.8)
            body_shape.left = Inches(0.5)
            body_shape.width = Inches(9.0) # 標準的なワイド(16:9でない場合)や4:3に合わせて調整
            body_shape.height = Inches(5.0)

            tf = body_shape.text_frame
            tf.word_wrap = True
            
            # コンテンツの流し込みと整形
            content_text = slide_info.get("content", "")
            
            # 先頭の・やスペースを削除（PPTXの箇条書き機能と重複しないように）
            cleaned_lines = []
            for line in content_text.split('\n'):
                # 全角・、半角・、スペースなどを削除
                cleaned_line = line.lstrip('・ ').lstrip()
                if cleaned_line:
                    cleaned_lines.append(cleaned_line)
            
            # 既存のパラグラフをクリアするのではなく、テキストを設定してから整形
            tf.text = "\n".join(cleaned_lines)
            
            for paragraph in tf.paragraphs:
                paragraph.font.name = FONT_NAME
                paragraph.font.size = Pt(28) # 少し大きめ
                paragraph.space_after = Pt(14) # 段落後のスペース
                paragraph.line_spacing = 1.3   # 行間を広げる
                
                # 行頭文字（・）の処理はpython-pptxのテンプレート依存だが、
                # インデントレベルなどが適切であればそのままでOK
            
            # --- ノート（キャプション/概要） ---
            notes_text = slide_info.get("caption", "")
            if "visual_logic" in slide_info:
                notes_text += f"\n\n[図解指示]\n{slide_info['visual_logic']}"

            if notes_text:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = notes_text

        output_path = "generated_presentation.pptx"
        self.prs.save(output_path)
        return output_path

if __name__ == "__main__":
    # Test
    gen = SlideGenerator()
    data = [
        {
            "title": "スライド1のタイトル", 
            "content": "・ポイント1\n・ポイント2", 
            "caption": "これはスライド1の概要です。",
            "visual_logic": "diagram: 対比図\nillustration: 笑顔の高齢者"
        },
        {
            "title": "スライド2のタイトル", 
            "content": "・ポイントA\n・ポイントB", 
            "caption": "これはスライド2の概要です。"
        }
    ]
    gen.create_slides("テストプレゼン", data)
    print("Test PPTX generated.")
